ARG AIRFLOW_BASE_IMAGE="apache/airflow:2.6.3-python3.8"
FROM ${AIRFLOW_BASE_IMAGE}

USER root
RUN apt-get update && apt-get install -y unzip
RUN mkdir -p /data && chown airflow /data
RUN mkdir -p /model && chown airflow /model
RUN mkdir -p /pickle && chown airflow /pickle



USER airflow
WORKDIR /app
COPY requirements.txt /app/
RUN pip install -r requirements.txt